version: '3.4'

services:
  projetocadastrocliente:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes:
      - dados-do-banco:/app/db
volumes:
  dados-do-banco: